name: Benchmarking

on: [ push, pull_request ]

jobs:
  test:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r tests/requirements_test.txt
      - name: Run benchmark
        run: pytest tests/bench.py --benchmark-json output.json --benchmark-min-rounds=1
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: output.json
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          alert-comment-cc-users: '@calebchiam'
