name: Benchmarking

on: [ push ]

jobs:
  test:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run benchmark
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r tests/requirements_test.txt
          pytest tests/bench.py --benchmark-json output.json --benchmark-min-rounds=1
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anishathalye'
